name: test-release

on:
    push:
        branches:
            - master
    workflow_run:
        workflows:
            - "production-tests"
        types:
            - completed
jobs:
    release:
        name: "Release on Test Pypi"
        runs-on: ubuntu-latest
        concurrency: release

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -   name: Test release on test pypi
                uses: relekang/python-semantic-release@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    repository_username: __token__
                    repository_password: ${{ secrets.TEST_PYPI_TOKEN }}
                    repository_url: https://test.pypi.org/legacy/
